name: Update Age in Profile

on:
  schedule:
    # Runs at 00:15 AM London time on August 5th
    # (23:15 UTC on August 4th during BST)
    - cron: '15 23 4 8 *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-age:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed so we can safely rebase before pushing

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update age in README
        run: python .github/scripts/update_age.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update age in profile"
            git pull --rebase
            git push
          else
            echo "No changes to commit."
          fi
