name: Anilist Watching/Reading Metrics
on:
  schedule: [{ cron: "30 0 */2 * *" }] # Every 2 days at 00:30
  workflow_dispatch: # Allow manual triggering
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Anilist Currently Watching Metrics
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/metrics.plugin.anilist.currently-watching.svg

          # Options
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favourites, watching
          plugin_anilist_limit: 4
          plugin_anilist_user: DaSushiAsian

      - name: Generate Anilist Currently Reading Metrics
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/metrics.plugin.anilist.currently-reading.svg

          # Options
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favourites, reading
          plugin_anilist_limit: 4
          plugin_anilist_user: DaSushiAsian

      # Added to update the README footer
      # Add Python setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Add required packages
      - name: Install dependencies
        run: pip install pyyaml croniter

      # Run the footer update script
      - name: Update dynamic footer
        run: python .github/scripts/update_footer.py

      # Commit changes if any
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git fetch
          git pull
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README dynamic footer" && git push)
