name: Spotify Recently Listened
on:
    schedule: [{cron: "0 * * * *"}] # Every hour
    workflow_dispatch: # Allow manual triggering
jobs:
    metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Generate Spotify Recently Listened Metrics
              uses: lowlighter/metrics@latest
              with:
                token: NOT_NEEDED
                filename: metrics/metrics.plugin.music.lastfm.artists.svg

                # Options
                base: ""
                plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
                plugin_music: yes
                plugin_music_provider: lastfm
                plugin_music_user: Lil_Sush
                plugin_music_time_range: long
                plugin_music_top_type: artists

            # Added to update the README footer
            # Add Python setup
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            # Add required packages
            - name: Install dependencies
              run: pip install pyyaml croniter

            # Run the footer update script
            - name: Update dynamic footer
              run: python .github/scripts/update_footer.py

            # Commit changes if any
            - name: Commit and push if changed
              run: |
                git config --global user.email "action@github.com"
                git config --global user.name "GitHub Action"
                git fetch
                git pull
                git add README.md
                git diff --quiet && git diff --staged --quiet || (git commit -m "Update README dynamic footer" && git push)
