name: Metrics
on:
    schedule: [{cron: "0 * * * *"}] # Every hour
    workflow_dispatch: # Allow manual triggering
jobs:
    metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                token: NOT_NEEDED

                # Options
                base: ""
                plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
                plugin_music: yes
                plugin_music_provider: lastfm
                plugin_music_user: Lil_Sush
                plugin_music_limit: 4
                plugin_music_time_range: short
