name: Spotify Recently Listed
on:
    schedule: [{cron: "0 * * * *"}] # Every hour
    workflow_dispatch: # Allow manual triggering
jobs:
    metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                token: NOT_NEEDED
                filename: metrics/metrics.plugin.music.recent.svg

                # Options
                base: ""
                plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
                plugin_music: yes
                plugin_music_provider: spotify
                plugin_music_mode: recent
                plugin_music_limit: 4
