name: Spotify Recently Listed
on:
    schedule: [{cron: "0 * * * *"}] # Every hour
    workflow_dispatch: # Allow manual triggering
jobs:
    metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v2

            - uses: lowlighter/metrics@latest
              with:
                token: NOT_NEEDED
                filename: metrics/metrics.plugin.music.recent.svg

                # Options
                base: ""
                plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
                plugin_music: yes
                plugin_music_provider: spotify
                plugin_music_mode: recent
                plugin_music_limit: 4

            # Added to update the README footer
            # Add Python setup
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            # Add required packages
            - name: Install dependencies
              run: pip install pyyaml croniter

            # Run the footer update script
            - name: Update dynamic footer
              run: python .github/scripts/update_footer.py

            # Commit changes if any
            - name: Commit and push if changed
              run: |
                git config --global user.email "action@github.com"
                git config --global user.name "GitHub Action"
                git add README.md
                git diff --quiet && git diff --staged --quiet || (git commit -m "Update README dynamic footer" && git push)